[profile.default]
optimizer_runs = 1000000
libs = ['node_modules', 'lib', "dependencies"]

[fuzz]
runs = 500
fail_on_revert = false
show_metrics = true

[fmt]
line_length = 100

[dependencies]
forge-std = "1.11.0"
